language: node_js
node_js:
- '10'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: Irs5+cbKO7n1QZl2oaiBSo73xe7nuPbuWcvkA/4batuzxf+aq03EyRk7yvo8BvysgAZ7nme/rBbpKaOW7dS/3TeKFYS5YFDnU7ax8s14/WDy2Y3ChFOAaVIHPk7E41Xl8p7IXP0MIoXdnIBYea1RmLWHQpJ92c/8+j5Lv7d/L3WtP++cJnJppZfK1tHVgdDjIpp6+acNFlpPUw8EpDOQ9jdFYj4LWorQ433eNtIq0iyOK2LNZ0m2QwfoVQ+xLpi4gXHXhJqeDLyLg7g1iMb1SlyQ/kEiDf7s5HBy3XW7A536bTgsM9sLeag8jWtjqXLWj0AlLuYKeSglqMoTxQrdKKaD/QWzspHjJuEVQfrHmhQ7chcMfBym5bVrU8fPK5hfftTxmt2tMTCPlG2BQeV8AXdk36SMqnq15EvQhvTbtqYeW9n24do9TwrJveRucEQUJxV/4/Nd20DaOCSLYT32WUAeXR1H0I+0qh0hSRBmuGc3awe1fMrJI6MLGBxdO+V1sgfBX0WvZcI2+Hiy6jDF3Vd5dUb7hAEa6g9nMupjhClVSW+Rbi0yloXCp0OX1qyxl6ALwVkKAiryRAp58PpkoKlam1C4/2gucvvOp3ow4uF2e8WLdeJao8Pc6Msu0FPfscBf/y9xybpTbiCsr6mu8QvggGy5ztCJD0FQ0n7DjUI=
